### ISSUE TITLE
Criar protótipo do aplicativo

### ISSUE THREAD

**Issue by LucasLermen** [Aquatop/Principal#1]
### Descrição:
Criar versão inicial do protótipo do app;

### Critérios de Aceitação
- [x] Possuir as principais telas do aplicativo

### Tarefas
- [x] Criar tela de login
- [x] Criar tela de cadastro de usuário
- [x] Criar tela de cadastro do aquario
- [x] Criar tela com dashboard de monitoramento 

### Comentários
Utilizar o figma

**Estimativa de Esforço** : 3 pontos

**Comment by LucasSiqz** [comment]
link de visualização do prototipo: https://www.figma.com/proto/DPwNFDTRYkOWOMF9hV7DPT/Aquatop?node-id=1%3A2&scaling=scale-down
