### ISSUE TITLE
Sensor de Nivel

### ISSUE THREAD

**Issue by alicefazz** [Aquatop/Principal#39]
### Descrição:

Colocar as  referências no texto conforme a norma ABNT , colocar em forma de tabela os parâmetros elétricos(por exemplo: corrente nominal, tensão de alimentação, potência , tipo de sinal obtido..), antes dos parâmetros explicar o que o sensor  faz e o pq  da gente tá escolhendo ele para o nosso projeto. Se tiver alguma fórmula, colocar a equação lá e explicar ela,  explicar também como funciona o circuito de operação e como é feita a aferição . 

### Critérios de Aceitação
Critérios de aceitação para a atividade ser aceita.

- [x] Conter todos os itens citados na descrição.

### Tarefas
Seção para tarefas (tasks) para atividades mais complexas. 
- [x] Listar todos os parâmetros para o sensor de Nível.

### Comentários
#BoraBora

**Estimativa de Esforço** : 3 pontos

**Comment by alicefazz** [comment]
Thiago, o texto tá top. Só alguns detalhes que eu acharia bom mudar. Por exemplo, a equação, será que não ficaria melhor colocar em formato de fórmula mesmo? (não sei se deu pra entender kkk). E a tabela vc pegou as especificações de um site, será que não seria melhor pegar do próprio datasheet? talvez eles achem melhor. E tá faltando a referência da imagem .

**Comment by Thiago-Bz** [comment]
Modifiquei la. A equação ja esta no formato de fórmula kkkk é que no docs fica zoado.
