### ISSUE TITLE
Sensor de PH

### ISSUE THREAD

**Issue by alicefazz** [Aquatop/Principal#40]
### Descrição:

Colocar as  referências no texto conforme a norma ABNT , colocar em forma de tabela os parâmetros elétricos(por exemplo: corrente nominal, tensão de alimentação, potência , tipo de sinal obtido..), antes dos parâmetros explicar o que o sensor  faz e o pq  da gente tá escolhendo ele para o nosso projeto. Se tiver alguma fórmula, colocar a equação lá e explicar ela,  explicar também como funciona o circuito de operação e como é feita a aferição . 

### Critérios de Aceitação
Critérios de aceitação para a atividade ser aceita.
- [ ]  Conter todos os itens citados na descrição.

### Tarefas
Seção para tarefas (tasks) para atividades mais complexas. 
- [ ] Listar todos os parâmetros para o sensor de PH.

### Comentários
#BoraBora

**Estimativa de Esforço** : 3 pontos

**Comment by alicefazz** [comment]
Gabriel, coloca as referências nas imagens, nas fórmulas, na tabela (recomendo pegar do datasheet). Então, o primeiro paragrafo tem que dar uma melhorada na escrita. Também tem que explicar melhor o funcionamento desse sensor, na hora de falar que o PH de 0 vale 0V e de 14 5V seria bom colocar aquela figurinha clássica que mostra que 0 à 6 é ácido e 8 à 14 é base. Também acho  que você tem que explicar melhor oq é esse módulo BNC, pra que serve e como fazer essa calibração. Ah, e essa Resolução acredito que tenha que explicar melhor tbm, inclusive a fórmula. Acho que tem que escrever pra uma pessoa quase totalemente leiga entender kkk

**Comment by alicefazz** [comment]
E não tem nenhuma outra fórmula não? pra fazer o calculo do PH? nada que envolva a temperatura sei lá? kkk aí n sei. É só essa aí mesmo da resolução?

**Comment by GabrielSSAraujo** [comment]
tem não, o calculo do ph é dado com uma variação de tensão no pino analógico ai so tem a alimentação e um pino de saida analógico.

**Comment by GabrielSSAraujo** [comment]
aquele pino de temperatura que tem lá é pra colocar um sensor de temperatura pra atuar junto com o sonda de PH tem uns pinos pra colocar o ds18b20 lá no modulo bnc
