### ISSUE TITLE
Sensor LDR

### ISSUE THREAD

**Issue by alicefazz** [Aquatop/Principal#41]
### Descrição:

  Colocar as  referências no texto conforme a norma ABNT , colocar em forma de tabela os parâmetros elétricos(por exemplo: corrente nominal, tensão de alimentação, potência , tipo de sinal obtido..), antes dos parâmetros explicar o que o sensor  faz e o pq  da gente tá escolhendo ele para o nosso projeto. Se tiver alguma fórmula, colocar a equação lá e explicar ela,  explicar também como funciona o circuito de operação e como é feita a aferição . 

### Critérios de Aceitação
Critérios de aceitação para a atividade ser aceita.
- [ ]  Conter todos os itens citados na descrição.

### Tarefas
Seção para tarefas (tasks) para atividades mais complexas. 
- [ ] Listar todos os parâmetros para o sensor de luminosidade.

### Comentários
#BoraBora

**Estimativa de Esforço** : 3 pontos

**Comment by joselitopradomarques** [comment]
Alice, fiz uma prévia do documento. Você poderia dar uma olhada e avaliá-lo, por favor?
[https://drive.google.com/open?id=1skeekE9MUUSXZxZpVJR0tg8NYITNTz0I](url)

**Comment by joselitopradomarques** [comment]
[LDR_explanation.docx](https://github.com/Aquatop/Principal/files/3623586/LDR_explanation.docx)
Consegui fazer o upload aqui. Está no Drive tbm. Tentei clicar no link mas me direcionou para outro lugar.
No drive: PI2>Eletrônica>Documentação>Sensores>LDR

**Comment by alicefazz** [comment]
Então, dá uma ajeitadinha no seu documento, coloca as  referências no texto conforme a norma ABNT , coloca em forma de tabela esses parâmetros elétricos tbm,  antes dos parâmetros explica o que o sensor LDR faz e o pq  da gente tá escolhendo ele para o nosso projeto. Se tiver alguma fórmula, coloca a equação lá e explica ela, tenta explicar melhor também como funciona o circuito de operação e como é feita a aferição . E o código pode colocar em outro documento na pasta de códigos.

**Comment by joselitopradomarques** [comment]
[LDR_explanation.docx](https://github.com/Aquatop/Principal/files/3643876/LDR_explanation.docx)
[ldr.txt](https://github.com/Aquatop/Principal/files/3643877/ldr.txt)

**Comment by alicefazz** [comment]
Então, vi que você colocou a referência lá na bibliografia, mas segundo a ABNT tem q ir referenciando no texto também. Tem que referenciar as imagens, as fórmulas, as tabelas (recomendo ser do datasheet). Tem um momento que vc escreve "Com a associação da resistência do LDR com a equação do comportamento da resistência em função da iluminância, pode-se determinar a luminosidade de um ambiente", mas qual equação é essa? Vc já citou? É a primeira? Se for tu pode colocar então : "Substituindo o valor da resistência do LDR na  equação 1 é possível determinar a luminosidade do ambiente". TIpo assim.. E alguns parágrafos acho que tá faltando citação indireta..

**Comment by alicefazz** [comment]
Coloca uma imagem do LDR tbm. :D

**Comment by joselitopradomarques** [comment]
Entendido. Faço hoje a noite e te respondo.

**Comment by joselitopradomarques** [comment]
Demorou mas fiz o update:

O link do documento se encontra abaixo: 
[LDR_explanation.docx](https://github.com/Aquatop/Principal/files/3664415/LDR_explanation.docx)

Qualquer modificação, pode avisar.

**Comment by joselitopradomarques** [comment]
Referências das imagens e da tabela inseridas.

[LDR_explanation.docx](https://github.com/Aquatop/Principal/files/3667992/LDR_explanation.docx)
