### ISSUE TITLE
Fluxograma 

### ISSUE THREAD

**Issue by alicefazz** [Aquatop/Principal#6]
### Descrição:
Criação de um fluxograma do comportamento do sistema eletrônico com todas suas comunicações

### Critérios de Aceitação
Critérios de aceitação para a atividade ser aceita.
- [x] Ligações entre componentes
- [ ] Protocolo de comunicação

### Tarefas
Seção para tarefas (tasks) para atividades mais complexas. 
- [x] Fluxograma contendo todos os componentes 

### Comentários
#borabora

**Estimativa de Esforço** : 8 pontos

**Comment by gabrieldouurado** [comment]
@alicefazz Essa parte do protocolo esta concluída tbm?
